### ISSUE TITLE
C++/CLI targeting .net core (.net 6)

### ISSUE THREAD

**Issue by HKunogi** [dotnet/core#6066]
When trying to make a new c++/cli project to target .net core instead of .net framework, or when changing an existing project to target it, it gives error when applying the setting. I've tried all different possible configurations on the project and it keeps on the same problem, I just cannot target the .net core on it.
![image](https://user-images.githubusercontent.com/1687701/111067976-1a291800-850a-11eb-9e86-9c60eb5a8336.png)

**Comment by antonfirsov** [comment]
@jkoritzinsky can you help with this?

**Comment by jkoritzinsky** [comment]
Does this occur with any .NET project or just C++/CLI?

**Comment by HKunogi** [comment]
> Does this occur with any .NET project or just C++/CLI?

This only happens when i try building an C++/CLI using netcore, if i use net framework it goes fine, and if i try to use c# it also goes fine.

**Comment by jkoritzinsky** [comment]
I'm not sure why the correct MSBuild files aren't being included.

@wli3 can you tag the C++ project system on this issue so they can take a look?

**Comment by wli3** [comment]
@olgaark

**Comment by olgaark** [comment]
Apparently, Microsoft.NET.ILLink.targets are using a property for the task location which is not defined in vcxproj, which imports common msbuild props/targets, but not c# ones. Run msbuild /pp on a c# project to see where this property is defined.

**Comment by wli3** [comment]
@agocke

**Comment by snikeguo** [comment]
up up.

**Comment by agocke** [comment]
This was probably fixed by https://github.com/dotnet/sdk/issues/16725

@HKunogi Can you try pulling a copy of the Preview 4 SDK from https://github.com/dotnet/installer and try your scenario again? Preview 4 should be available very soon.

@olgaark It looks like the root cause is the SDK targets are imported, but not the props. https://github.com/dotnet/sdk/issues/16725#issuecomment-813456887 Is there a particular reason for this? Importing the props and not the targets is likely to cause these types of failures.

**Comment by olgaark** [comment]
VC projects are importing what SDK people told us to import, I don't know the reason. If we need to import more, just let us know.

**Comment by wli3** [comment]
C++/CLI does not support nuget restore yet. So any props and target require that to work will not be imported. You can try to add that to part of the import (search for '$(Language)' != 'C++') and then test. If it works you start to include that props or targets.

**Comment by kzhui125** [comment]
any updates, it seems VS2022 C++ clr can't target .net 6

**Comment by kzhui125** [comment]
.net 5 End of support is May 08, 2022

but now VS 2022 C++ clr still doesn't support .NET 6!!!!!!

**Comment by kzhui125** [comment]
<img width="949" alt="1" src="https://user-images.githubusercontent.com/11925432/163682265-ef874f10-4da4-4a84-831d-15c0fe884375.png">


There is only .net core 3.1 and .net 5, still no .net 6 support now!!

**Comment by agocke** [comment]
This issue was previously describing a problem with C++/CLI colliding with the ILLink targets. That issue is now fixed. This appears to be a different problem. I'm opening a new issue for it.

**Comment by agocke** [comment]
Actually, this appears to be specific to Visual Studio -- please open a [VS feedback issue](https://developercommunity.visualstudio.com/home) if you are having issues with Visual Studio.
