### ISSUE TITLE
version api used by dotnet-install-script returns SDK version 6.0.103 instead of 6.0.201

### ISSUE THREAD

**Issue by csMACnz** [dotnet/core#7267]
### Description

The endpoints used by the [dotnet-install-script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) is returning version 6.0.103 as the latest instead of 6.0.201 as expected. Are my expectations wrong, or did this get updated to the wrong new version (I see both versions were released yesterday?)

Steps to reproduce: 
* Go to url `https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0/latest.version` and see the result
* (See also `https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version`)
* Expected: 6.0.201
* Actual: 6.0.103

As a cross reference to which one is the right answe, the 6.0 releases json in this repo appears to correctly report 6.0.201 as expected:
https://github.com/dotnet/core/blob/3e1c9ee32b3b9afac52db09fa840e84729e4caa8/release-notes/6.0/releases.json#L6

**Comment by csMACnz** [comment]
I was reading this value for some upgrade automation scripts.
As a workaround I've managed to point it at the publicly readable [/release-notes/6.0/releases.json](https://raw.githubusercontent.com/dotnet/core/main/release-notes/6.0/releases.json) file to parse out the 6.0.201 value as expected.

**Comment by mairaw** [comment]
@adiaaida I think you were looking into this today, no? I can repro the behavior above

**Comment by mairaw** [comment]
Also tagging @rbhanda and @dcwhittaker

**Comment by adiaaida** [comment]
This should have been fixed as of ~3pm today.

**Comment by dcwhittaker** [comment]
Latest.version is updated.

**Comment by csMACnz** [comment]
Great, I can see that is updated now 👍

**Comment by mairaw** [comment]
I still see 103 for https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version. Is it expected?

**Comment by dcwhittaker** [comment]
@mairaw - when I open the link I see 6.0.201...

**Comment by mairaw** [comment]
I see it now too. So closing the issue then since everything seems to be resolved.
